<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Login.proto

namespace GPBMetadata;

class Login
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a460a0b4c6f67696e2e70726f746f222f0a094c6f67696e496e666f1210" .
            "0a08757365726e616d6518012001280912100a0870617373776f72641802" .
            "20012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

