<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LoginProtocol.proto

namespace Logic\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *账号信息
 *
 * Generated from protobuf message <code>Logic.Protocol.AccountInfo</code>
 */
class AccountInfo extends \Google\Protobuf\Internal\Message
{
    /**
     *uId
     *
     * Generated from protobuf field <code>int32 uId = 1;</code>
     */
    private $uId = 0;
    /**
     *用户名
     *
     * Generated from protobuf field <code>bytes username = 2;</code>
     */
    private $username = '';
    /**
     *密码
     *
     * Generated from protobuf field <code>bytes password = 3;</code>
     */
    private $password = '';
    /**
     *openID
     *
     * Generated from protobuf field <code>bytes openId = 4;</code>
     */
    private $openId = '';
    /**
     *注册类型
     *
     * Generated from protobuf field <code>.Logic.Protocol.LoginType loginType = 5;</code>
     */
    private $loginType = 0;
    /**
     *终端类型
     *
     * Generated from protobuf field <code>.Logic.Protocol.OSType osType = 6;</code>
     */
    private $osType = 0;
    /**
     *第三方渠道号
     *
     * Generated from protobuf field <code>int32 channel = 7;</code>
     */
    private $channel = 0;
    /**
     *注册时间
     *
     * Generated from protobuf field <code>bytes registTime = 8;</code>
     */
    private $registTime = '';

    public function __construct() {
        \GPBMetadata\LoginProtocol::initOnce();
        parent::__construct();
    }

    /**
     *uId
     *
     * Generated from protobuf field <code>int32 uId = 1;</code>
     * @return int
     */
    public function getUId()
    {
        return $this->uId;
    }

    /**
     *uId
     *
     * Generated from protobuf field <code>int32 uId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setUId($var)
    {
        GPBUtil::checkInt32($var);
        $this->uId = $var;

        return $this;
    }

    /**
     *用户名
     *
     * Generated from protobuf field <code>bytes username = 2;</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     *用户名
     *
     * Generated from protobuf field <code>bytes username = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, False);
        $this->username = $var;

        return $this;
    }

    /**
     *密码
     *
     * Generated from protobuf field <code>bytes password = 3;</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     *密码
     *
     * Generated from protobuf field <code>bytes password = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, False);
        $this->password = $var;

        return $this;
    }

    /**
     *openID
     *
     * Generated from protobuf field <code>bytes openId = 4;</code>
     * @return string
     */
    public function getOpenId()
    {
        return $this->openId;
    }

    /**
     *openID
     *
     * Generated from protobuf field <code>bytes openId = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setOpenId($var)
    {
        GPBUtil::checkString($var, False);
        $this->openId = $var;

        return $this;
    }

    /**
     *注册类型
     *
     * Generated from protobuf field <code>.Logic.Protocol.LoginType loginType = 5;</code>
     * @return int
     */
    public function getLoginType()
    {
        return $this->loginType;
    }

    /**
     *注册类型
     *
     * Generated from protobuf field <code>.Logic.Protocol.LoginType loginType = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setLoginType($var)
    {
        GPBUtil::checkEnum($var, \Logic\Protocol\LoginType::class);
        $this->loginType = $var;

        return $this;
    }

    /**
     *终端类型
     *
     * Generated from protobuf field <code>.Logic.Protocol.OSType osType = 6;</code>
     * @return int
     */
    public function getOsType()
    {
        return $this->osType;
    }

    /**
     *终端类型
     *
     * Generated from protobuf field <code>.Logic.Protocol.OSType osType = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setOsType($var)
    {
        GPBUtil::checkEnum($var, \Logic\Protocol\OSType::class);
        $this->osType = $var;

        return $this;
    }

    /**
     *第三方渠道号
     *
     * Generated from protobuf field <code>int32 channel = 7;</code>
     * @return int
     */
    public function getChannel()
    {
        return $this->channel;
    }

    /**
     *第三方渠道号
     *
     * Generated from protobuf field <code>int32 channel = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setChannel($var)
    {
        GPBUtil::checkInt32($var);
        $this->channel = $var;

        return $this;
    }

    /**
     *注册时间
     *
     * Generated from protobuf field <code>bytes registTime = 8;</code>
     * @return string
     */
    public function getRegistTime()
    {
        return $this->registTime;
    }

    /**
     *注册时间
     *
     * Generated from protobuf field <code>bytes registTime = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setRegistTime($var)
    {
        GPBUtil::checkString($var, False);
        $this->registTime = $var;

        return $this;
    }

}

