<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PlayerProtocol.proto

namespace Logic\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *玩家基本信息
 *
 * Generated from protobuf message <code>Logic.Protocol.PlayerBasicInfo</code>
 */
class PlayerBasicInfo extends \Google\Protobuf\Internal\Message
{
    /**
     *昵称
     *
     * Generated from protobuf field <code>bytes name = 1;</code>
     */
    private $name = '';
    /**
     *状态
     *
     * Generated from protobuf field <code>.Logic.Protocol.PlayerState state = 2;</code>
     */
    private $state = 0;
    /**
     *性别
     *
     * Generated from protobuf field <code>uint32 sex = 3;</code>
     */
    private $sex = 0;
    /**
     *注册时间
     *
     * Generated from protobuf field <code>uint64 registTime = 4;</code>
     */
    private $registTime = 0;
    /**
     *上次登陆时间
     *
     * Generated from protobuf field <code>uint64 lastLoginTime = 5;</code>
     */
    private $lastLoginTime = 0;

    public function __construct() {
        \GPBMetadata\PlayerProtocol::initOnce();
        parent::__construct();
    }

    /**
     *昵称
     *
     * Generated from protobuf field <code>bytes name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     *昵称
     *
     * Generated from protobuf field <code>bytes name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, False);
        $this->name = $var;

        return $this;
    }

    /**
     *状态
     *
     * Generated from protobuf field <code>.Logic.Protocol.PlayerState state = 2;</code>
     * @return int
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     *状态
     *
     * Generated from protobuf field <code>.Logic.Protocol.PlayerState state = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setState($var)
    {
        GPBUtil::checkEnum($var, \Logic\Protocol\PlayerState::class);
        $this->state = $var;

        return $this;
    }

    /**
     *性别
     *
     * Generated from protobuf field <code>uint32 sex = 3;</code>
     * @return int
     */
    public function getSex()
    {
        return $this->sex;
    }

    /**
     *性别
     *
     * Generated from protobuf field <code>uint32 sex = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setSex($var)
    {
        GPBUtil::checkUint32($var);
        $this->sex = $var;

        return $this;
    }

    /**
     *注册时间
     *
     * Generated from protobuf field <code>uint64 registTime = 4;</code>
     * @return int|string
     */
    public function getRegistTime()
    {
        return $this->registTime;
    }

    /**
     *注册时间
     *
     * Generated from protobuf field <code>uint64 registTime = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRegistTime($var)
    {
        GPBUtil::checkUint64($var);
        $this->registTime = $var;

        return $this;
    }

    /**
     *上次登陆时间
     *
     * Generated from protobuf field <code>uint64 lastLoginTime = 5;</code>
     * @return int|string
     */
    public function getLastLoginTime()
    {
        return $this->lastLoginTime;
    }

    /**
     *上次登陆时间
     *
     * Generated from protobuf field <code>uint64 lastLoginTime = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLastLoginTime($var)
    {
        GPBUtil::checkUint64($var);
        $this->lastLoginTime = $var;

        return $this;
    }

}

