<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProtocolCmd.proto

namespace Logic\Protocol;

/**
 * Protobuf enum <code>Logic\Protocol\ProtocolCmd</code>
 */
class ProtocolCmd
{
    /**
     * Generated from protobuf enum <code>CMD_TYPE = 0;</code>
     */
    const CMD_TYPE = 0;
    /**
     *心跳
     *
     * Generated from protobuf enum <code>CMD_PING = 1;</code>
     */
    const CMD_PING = 1;
    /**
     * Generated from protobuf enum <code>CMD_PONG = 2;</code>
     */
    const CMD_PONG = 2;
    /**
     *4位作为CMD命令，不同开头功能不同
     *
     * Generated from protobuf enum <code>MESSAGE_TYPE_SYSTEM = 4096;</code>
     */
    const MESSAGE_TYPE_SYSTEM = 4096;
    /**
     *注册
     *
     * Generated from protobuf enum <code>CMD_REGIST_REQ = 4097;</code>
     */
    const CMD_REGIST_REQ = 4097;
    /**
     * Generated from protobuf enum <code>CMD_REGIST_RESP = 4098;</code>
     */
    const CMD_REGIST_RESP = 4098;
    /**
     *登陆
     *
     * Generated from protobuf enum <code>CMD_LOGIN_REQ = 4099;</code>
     */
    const CMD_LOGIN_REQ = 4099;
    /**
     * Generated from protobuf enum <code>CMD_LOGIN_RESP = 4100;</code>
     */
    const CMD_LOGIN_RESP = 4100;
    /**
     *退出
     *
     * Generated from protobuf enum <code>CMD_LOGOUT_REQ = 4101;</code>
     */
    const CMD_LOGOUT_REQ = 4101;
    /**
     * Generated from protobuf enum <code>CMD_LOGOUT_RESP = 4102;</code>
     */
    const CMD_LOGOUT_RESP = 4102;
}

