<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LoginProtocol.proto

namespace Logic\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *注册请求
 *
 * Generated from protobuf message <code>Logic.Protocol.RegistReq</code>
 */
class RegistReq extends \Google\Protobuf\Internal\Message
{
    /**
     *用户名
     *
     * Generated from protobuf field <code>bytes username = 1;</code>
     */
    private $username = '';
    /**
     *密码
     *
     * Generated from protobuf field <code>bytes password = 2;</code>
     */
    private $password = '';
    /**
     *openID
     *
     * Generated from protobuf field <code>bytes openId = 3;</code>
     */
    private $openId = '';
    /**
     *注册类型
     *
     * Generated from protobuf field <code>.Logic.Protocol.LoginType loginType = 4;</code>
     */
    private $loginType = 0;
    /**
     *玩家的机器相关信息（用于数据统计）
     *
     * Generated from protobuf field <code>.Logic.Protocol.PlayerEnvInfo playerEnvInfo = 5;</code>
     */
    private $playerEnvInfo = null;
    /**
     *玩家终端类型
     *
     * Generated from protobuf field <code>.Logic.Protocol.OSType osType = 6;</code>
     */
    private $osType = 0;
    /**
     *第三方渠道号
     *
     * Generated from protobuf field <code>int32 channel = 7;</code>
     */
    private $channel = 0;

    public function __construct() {
        \GPBMetadata\LoginProtocol::initOnce();
        parent::__construct();
    }

    /**
     *用户名
     *
     * Generated from protobuf field <code>bytes username = 1;</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     *用户名
     *
     * Generated from protobuf field <code>bytes username = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, False);
        $this->username = $var;

        return $this;
    }

    /**
     *密码
     *
     * Generated from protobuf field <code>bytes password = 2;</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     *密码
     *
     * Generated from protobuf field <code>bytes password = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, False);
        $this->password = $var;

        return $this;
    }

    /**
     *openID
     *
     * Generated from protobuf field <code>bytes openId = 3;</code>
     * @return string
     */
    public function getOpenId()
    {
        return $this->openId;
    }

    /**
     *openID
     *
     * Generated from protobuf field <code>bytes openId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setOpenId($var)
    {
        GPBUtil::checkString($var, False);
        $this->openId = $var;

        return $this;
    }

    /**
     *注册类型
     *
     * Generated from protobuf field <code>.Logic.Protocol.LoginType loginType = 4;</code>
     * @return int
     */
    public function getLoginType()
    {
        return $this->loginType;
    }

    /**
     *注册类型
     *
     * Generated from protobuf field <code>.Logic.Protocol.LoginType loginType = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setLoginType($var)
    {
        GPBUtil::checkEnum($var, \Logic\Protocol\LoginType::class);
        $this->loginType = $var;

        return $this;
    }

    /**
     *玩家的机器相关信息（用于数据统计）
     *
     * Generated from protobuf field <code>.Logic.Protocol.PlayerEnvInfo playerEnvInfo = 5;</code>
     * @return \Logic\Protocol\PlayerEnvInfo
     */
    public function getPlayerEnvInfo()
    {
        return $this->playerEnvInfo;
    }

    /**
     *玩家的机器相关信息（用于数据统计）
     *
     * Generated from protobuf field <code>.Logic.Protocol.PlayerEnvInfo playerEnvInfo = 5;</code>
     * @param \Logic\Protocol\PlayerEnvInfo $var
     * @return $this
     */
    public function setPlayerEnvInfo($var)
    {
        GPBUtil::checkMessage($var, \Logic\Protocol\PlayerEnvInfo::class);
        $this->playerEnvInfo = $var;

        return $this;
    }

    /**
     *玩家终端类型
     *
     * Generated from protobuf field <code>.Logic.Protocol.OSType osType = 6;</code>
     * @return int
     */
    public function getOsType()
    {
        return $this->osType;
    }

    /**
     *玩家终端类型
     *
     * Generated from protobuf field <code>.Logic.Protocol.OSType osType = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setOsType($var)
    {
        GPBUtil::checkEnum($var, \Logic\Protocol\OSType::class);
        $this->osType = $var;

        return $this;
    }

    /**
     *第三方渠道号
     *
     * Generated from protobuf field <code>int32 channel = 7;</code>
     * @return int
     */
    public function getChannel()
    {
        return $this->channel;
    }

    /**
     *第三方渠道号
     *
     * Generated from protobuf field <code>int32 channel = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setChannel($var)
    {
        GPBUtil::checkInt32($var);
        $this->channel = $var;

        return $this;
    }

}

