<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LoginProtocol.proto

namespace Logic\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *注册响应
 *
 * Generated from protobuf message <code>Logic.Protocol.RegistResp</code>
 */
class RegistResp extends \Google\Protobuf\Internal\Message
{
    /**
     *返回值
     *
     * Generated from protobuf field <code>int32 ret = 1;</code>
     */
    private $ret = 0;
    /**
     *uId
     *
     * Generated from protobuf field <code>int32 uId = 2;</code>
     */
    private $uId = 0;
    /**
     *登陆Token，通常有登陆服务器的情况下，登陆服务器返回的Token，并用这个Token和网关进行验证
     *
     * Generated from protobuf field <code>bytes loginToken = 3;</code>
     */
    private $loginToken = '';

    public function __construct() {
        \GPBMetadata\LoginProtocol::initOnce();
        parent::__construct();
    }

    /**
     *返回值
     *
     * Generated from protobuf field <code>int32 ret = 1;</code>
     * @return int
     */
    public function getRet()
    {
        return $this->ret;
    }

    /**
     *返回值
     *
     * Generated from protobuf field <code>int32 ret = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setRet($var)
    {
        GPBUtil::checkInt32($var);
        $this->ret = $var;

        return $this;
    }

    /**
     *uId
     *
     * Generated from protobuf field <code>int32 uId = 2;</code>
     * @return int
     */
    public function getUId()
    {
        return $this->uId;
    }

    /**
     *uId
     *
     * Generated from protobuf field <code>int32 uId = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setUId($var)
    {
        GPBUtil::checkInt32($var);
        $this->uId = $var;

        return $this;
    }

    /**
     *登陆Token，通常有登陆服务器的情况下，登陆服务器返回的Token，并用这个Token和网关进行验证
     *
     * Generated from protobuf field <code>bytes loginToken = 3;</code>
     * @return string
     */
    public function getLoginToken()
    {
        return $this->loginToken;
    }

    /**
     *登陆Token，通常有登陆服务器的情况下，登陆服务器返回的Token，并用这个Token和网关进行验证
     *
     * Generated from protobuf field <code>bytes loginToken = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setLoginToken($var)
    {
        GPBUtil::checkString($var, False);
        $this->loginToken = $var;

        return $this;
    }

}

