<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RetCode.proto

namespace GPBMetadata;

class RetCode
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a530a0d526574436f64652e70726f746f120e4c6f6769632e50726f746f" .
            "636f6c2a2a0a07526574436f6465120b0a0753554343455353100012120a" .
            "0d5245474953545f4641494c4544108020620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

