<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LoginProtocol.proto

namespace Logic\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *登陆请求
 *
 * Generated from protobuf message <code>Logic.Protocol.LoginReq</code>
 */
class LoginReq extends \Google\Protobuf\Internal\Message
{
    /**
     *用户名   
     *
     * Generated from protobuf field <code>bytes username = 1;</code>
     */
    private $username = '';
    /**
     *密码
     *
     * Generated from protobuf field <code>bytes password = 2;</code>
     */
    private $password = '';
    /**
     *openId，通常情况下openID为第三方渠道请求后获得的唯一标识，根据业务逻辑和接入渠道情况自行定义
     *
     * Generated from protobuf field <code>bytes openId = 3;</code>
     */
    private $openId = '';
    /**
     *uId，如果在有单独登陆服务器的情况下，通常uId作为唯一ID标识
     *
     * Generated from protobuf field <code>int32 uId = 4;</code>
     */
    private $uId = 0;
    /**
     *登陆Token，通常有登陆服务器的情况下，登陆服务器返回的Token，并用这个Token和网关进行验证
     *
     * Generated from protobuf field <code>bytes loginToken = 5;</code>
     */
    private $loginToken = '';
    /**
     *登陆类型（参照上面的枚举）
     *
     * Generated from protobuf field <code>.Logic.Protocol.LoginType loginType = 6;</code>
     */
    private $loginType = 0;
    /**
     *玩家的机器相关信息（用于数据统计）
     *
     * Generated from protobuf field <code>.Logic.Protocol.PlayerEnvInfo playerEnvInfo = 7;</code>
     */
    private $playerEnvInfo = null;
    /**
     *用于消息推送使用，一般来说用deviceId即可
     *
     * Generated from protobuf field <code>bytes deviceCode = 8;</code>
     */
    private $deviceCode = '';
    /**
     *玩家终端类型
     *
     * Generated from protobuf field <code>.Logic.Protocol.OSType osType = 9;</code>
     */
    private $osType = 0;
    /**
     *第三方渠道号
     *
     * Generated from protobuf field <code>int32 channel = 10;</code>
     */
    private $channel = 0;
    /**
     *玩家连接服务器ID
     *
     * Generated from protobuf field <code>int32 svrId = 11;</code>
     */
    private $svrId = 0;

    public function __construct() {
        \GPBMetadata\LoginProtocol::initOnce();
        parent::__construct();
    }

    /**
     *用户名   
     *
     * Generated from protobuf field <code>bytes username = 1;</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     *用户名   
     *
     * Generated from protobuf field <code>bytes username = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, False);
        $this->username = $var;

        return $this;
    }

    /**
     *密码
     *
     * Generated from protobuf field <code>bytes password = 2;</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     *密码
     *
     * Generated from protobuf field <code>bytes password = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, False);
        $this->password = $var;

        return $this;
    }

    /**
     *openId，通常情况下openID为第三方渠道请求后获得的唯一标识，根据业务逻辑和接入渠道情况自行定义
     *
     * Generated from protobuf field <code>bytes openId = 3;</code>
     * @return string
     */
    public function getOpenId()
    {
        return $this->openId;
    }

    /**
     *openId，通常情况下openID为第三方渠道请求后获得的唯一标识，根据业务逻辑和接入渠道情况自行定义
     *
     * Generated from protobuf field <code>bytes openId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setOpenId($var)
    {
        GPBUtil::checkString($var, False);
        $this->openId = $var;

        return $this;
    }

    /**
     *uId，如果在有单独登陆服务器的情况下，通常uId作为唯一ID标识
     *
     * Generated from protobuf field <code>int32 uId = 4;</code>
     * @return int
     */
    public function getUId()
    {
        return $this->uId;
    }

    /**
     *uId，如果在有单独登陆服务器的情况下，通常uId作为唯一ID标识
     *
     * Generated from protobuf field <code>int32 uId = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setUId($var)
    {
        GPBUtil::checkInt32($var);
        $this->uId = $var;

        return $this;
    }

    /**
     *登陆Token，通常有登陆服务器的情况下，登陆服务器返回的Token，并用这个Token和网关进行验证
     *
     * Generated from protobuf field <code>bytes loginToken = 5;</code>
     * @return string
     */
    public function getLoginToken()
    {
        return $this->loginToken;
    }

    /**
     *登陆Token，通常有登陆服务器的情况下，登陆服务器返回的Token，并用这个Token和网关进行验证
     *
     * Generated from protobuf field <code>bytes loginToken = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setLoginToken($var)
    {
        GPBUtil::checkString($var, False);
        $this->loginToken = $var;

        return $this;
    }

    /**
     *登陆类型（参照上面的枚举）
     *
     * Generated from protobuf field <code>.Logic.Protocol.LoginType loginType = 6;</code>
     * @return int
     */
    public function getLoginType()
    {
        return $this->loginType;
    }

    /**
     *登陆类型（参照上面的枚举）
     *
     * Generated from protobuf field <code>.Logic.Protocol.LoginType loginType = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setLoginType($var)
    {
        GPBUtil::checkEnum($var, \Logic\Protocol\LoginType::class);
        $this->loginType = $var;

        return $this;
    }

    /**
     *玩家的机器相关信息（用于数据统计）
     *
     * Generated from protobuf field <code>.Logic.Protocol.PlayerEnvInfo playerEnvInfo = 7;</code>
     * @return \Logic\Protocol\PlayerEnvInfo
     */
    public function getPlayerEnvInfo()
    {
        return $this->playerEnvInfo;
    }

    /**
     *玩家的机器相关信息（用于数据统计）
     *
     * Generated from protobuf field <code>.Logic.Protocol.PlayerEnvInfo playerEnvInfo = 7;</code>
     * @param \Logic\Protocol\PlayerEnvInfo $var
     * @return $this
     */
    public function setPlayerEnvInfo($var)
    {
        GPBUtil::checkMessage($var, \Logic\Protocol\PlayerEnvInfo::class);
        $this->playerEnvInfo = $var;

        return $this;
    }

    /**
     *用于消息推送使用，一般来说用deviceId即可
     *
     * Generated from protobuf field <code>bytes deviceCode = 8;</code>
     * @return string
     */
    public function getDeviceCode()
    {
        return $this->deviceCode;
    }

    /**
     *用于消息推送使用，一般来说用deviceId即可
     *
     * Generated from protobuf field <code>bytes deviceCode = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceCode($var)
    {
        GPBUtil::checkString($var, False);
        $this->deviceCode = $var;

        return $this;
    }

    /**
     *玩家终端类型
     *
     * Generated from protobuf field <code>.Logic.Protocol.OSType osType = 9;</code>
     * @return int
     */
    public function getOsType()
    {
        return $this->osType;
    }

    /**
     *玩家终端类型
     *
     * Generated from protobuf field <code>.Logic.Protocol.OSType osType = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setOsType($var)
    {
        GPBUtil::checkEnum($var, \Logic\Protocol\OSType::class);
        $this->osType = $var;

        return $this;
    }

    /**
     *第三方渠道号
     *
     * Generated from protobuf field <code>int32 channel = 10;</code>
     * @return int
     */
    public function getChannel()
    {
        return $this->channel;
    }

    /**
     *第三方渠道号
     *
     * Generated from protobuf field <code>int32 channel = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setChannel($var)
    {
        GPBUtil::checkInt32($var);
        $this->channel = $var;

        return $this;
    }

    /**
     *玩家连接服务器ID
     *
     * Generated from protobuf field <code>int32 svrId = 11;</code>
     * @return int
     */
    public function getSvrId()
    {
        return $this->svrId;
    }

    /**
     *玩家连接服务器ID
     *
     * Generated from protobuf field <code>int32 svrId = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setSvrId($var)
    {
        GPBUtil::checkInt32($var);
        $this->svrId = $var;

        return $this;
    }

}

