<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LoginProtocol.proto

namespace Logic\Protocol;

/**
 *终端类型
 *
 * Protobuf enum <code>Logic\Protocol\OSType</code>
 */
class OSType
{
    /**
     *默认不使用
     *
     * Generated from protobuf enum <code>OS_TYPE_DEFAULT = 0;</code>
     */
    const OS_TYPE_DEFAULT = 0;
    /**
     *PC
     *
     * Generated from protobuf enum <code>OS_TYPE_PC = 1;</code>
     */
    const OS_TYPE_PC = 1;
    /**
     *Mac
     *
     * Generated from protobuf enum <code>OS_TYPE_MAC = 2;</code>
     */
    const OS_TYPE_MAC = 2;
    /**
     *web
     *
     * Generated from protobuf enum <code>OS_TYPE_WEB = 3;</code>
     */
    const OS_TYPE_WEB = 3;
    /**
     *IOS
     *
     * Generated from protobuf enum <code>OS_TYPE_IOS = 4;</code>
     */
    const OS_TYPE_IOS = 4;
    /**
     *安卓
     *
     * Generated from protobuf enum <code>OS_TYPE_ANDROID = 5;</code>
     */
    const OS_TYPE_ANDROID = 5;
}

