<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LoginProtocol.proto

namespace Logic\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *玩家的设备相关信息，用于日志统计的信息（在玩家注册和登陆时上报该内容）
 *
 * Generated from protobuf message <code>Logic.Protocol.PlayerEnvInfo</code>
 */
class PlayerEnvInfo extends \Google\Protobuf\Internal\Message
{
    /**
     *客户端版本
     *
     * Generated from protobuf field <code>bytes clientVersion = 1;</code>
     */
    private $clientVersion = '';
    /**
     *操作系统版本
     *
     * Generated from protobuf field <code>bytes systemSoft = 2;</code>
     */
    private $systemSoft = '';
    /**
     *终端机型设备
     *
     * Generated from protobuf field <code>bytes systemHardware = 3;</code>
     */
    private $systemHardware = '';
    /**
     *运营商
     *
     * Generated from protobuf field <code>bytes telecom = 4;</code>
     */
    private $telecom = '';
    /**
     *3G/4G/WIFI/2G
     *
     * Generated from protobuf field <code>bytes network = 5;</code>
     */
    private $network = '';
    /**
     *屏幕宽度
     *
     * Generated from protobuf field <code>bytes screenWidth = 6;</code>
     */
    private $screenWidth = '';
    /**
     *屏幕高度
     *
     * Generated from protobuf field <code>bytes screenHeight = 7;</code>
     */
    private $screenHeight = '';
    /**
     *屏幕像素密度
     *
     * Generated from protobuf field <code>bytes density = 8;</code>
     */
    private $density = '';
    /**
     *注册渠道
     *
     * Generated from protobuf field <code>bytes channel = 9;</code>
     */
    private $channel = '';
    /**
     *唯一ID(可用MAC、UDID等信息做标识)
     *
     * Generated from protobuf field <code>bytes uuid = 10;</code>
     */
    private $uuid = '';
    /**
     *CPU类型|频率|核数
     *
     * Generated from protobuf field <code>bytes cpuHardware = 11;</code>
     */
    private $cpuHardware = '';
    /**
     *内存大小 单位为MB
     *
     * Generated from protobuf field <code>bytes memory = 12;</code>
     */
    private $memory = '';
    /**
     *OpenGL render信息
     *
     * Generated from protobuf field <code>bytes glRender = 13;</code>
     */
    private $glRender = '';
    /**
     *OpenGL 版本信息
     *
     * Generated from protobuf field <code>bytes glVersion = 14;</code>
     */
    private $glVersion = '';
    /**
     *设备ID
     *
     * Generated from protobuf field <code>bytes deviceId = 15;</code>
     */
    private $deviceId = '';

    public function __construct() {
        \GPBMetadata\LoginProtocol::initOnce();
        parent::__construct();
    }

    /**
     *客户端版本
     *
     * Generated from protobuf field <code>bytes clientVersion = 1;</code>
     * @return string
     */
    public function getClientVersion()
    {
        return $this->clientVersion;
    }

    /**
     *客户端版本
     *
     * Generated from protobuf field <code>bytes clientVersion = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setClientVersion($var)
    {
        GPBUtil::checkString($var, False);
        $this->clientVersion = $var;

        return $this;
    }

    /**
     *操作系统版本
     *
     * Generated from protobuf field <code>bytes systemSoft = 2;</code>
     * @return string
     */
    public function getSystemSoft()
    {
        return $this->systemSoft;
    }

    /**
     *操作系统版本
     *
     * Generated from protobuf field <code>bytes systemSoft = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSystemSoft($var)
    {
        GPBUtil::checkString($var, False);
        $this->systemSoft = $var;

        return $this;
    }

    /**
     *终端机型设备
     *
     * Generated from protobuf field <code>bytes systemHardware = 3;</code>
     * @return string
     */
    public function getSystemHardware()
    {
        return $this->systemHardware;
    }

    /**
     *终端机型设备
     *
     * Generated from protobuf field <code>bytes systemHardware = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSystemHardware($var)
    {
        GPBUtil::checkString($var, False);
        $this->systemHardware = $var;

        return $this;
    }

    /**
     *运营商
     *
     * Generated from protobuf field <code>bytes telecom = 4;</code>
     * @return string
     */
    public function getTelecom()
    {
        return $this->telecom;
    }

    /**
     *运营商
     *
     * Generated from protobuf field <code>bytes telecom = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setTelecom($var)
    {
        GPBUtil::checkString($var, False);
        $this->telecom = $var;

        return $this;
    }

    /**
     *3G/4G/WIFI/2G
     *
     * Generated from protobuf field <code>bytes network = 5;</code>
     * @return string
     */
    public function getNetwork()
    {
        return $this->network;
    }

    /**
     *3G/4G/WIFI/2G
     *
     * Generated from protobuf field <code>bytes network = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setNetwork($var)
    {
        GPBUtil::checkString($var, False);
        $this->network = $var;

        return $this;
    }

    /**
     *屏幕宽度
     *
     * Generated from protobuf field <code>bytes screenWidth = 6;</code>
     * @return string
     */
    public function getScreenWidth()
    {
        return $this->screenWidth;
    }

    /**
     *屏幕宽度
     *
     * Generated from protobuf field <code>bytes screenWidth = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setScreenWidth($var)
    {
        GPBUtil::checkString($var, False);
        $this->screenWidth = $var;

        return $this;
    }

    /**
     *屏幕高度
     *
     * Generated from protobuf field <code>bytes screenHeight = 7;</code>
     * @return string
     */
    public function getScreenHeight()
    {
        return $this->screenHeight;
    }

    /**
     *屏幕高度
     *
     * Generated from protobuf field <code>bytes screenHeight = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setScreenHeight($var)
    {
        GPBUtil::checkString($var, False);
        $this->screenHeight = $var;

        return $this;
    }

    /**
     *屏幕像素密度
     *
     * Generated from protobuf field <code>bytes density = 8;</code>
     * @return string
     */
    public function getDensity()
    {
        return $this->density;
    }

    /**
     *屏幕像素密度
     *
     * Generated from protobuf field <code>bytes density = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setDensity($var)
    {
        GPBUtil::checkString($var, False);
        $this->density = $var;

        return $this;
    }

    /**
     *注册渠道
     *
     * Generated from protobuf field <code>bytes channel = 9;</code>
     * @return string
     */
    public function getChannel()
    {
        return $this->channel;
    }

    /**
     *注册渠道
     *
     * Generated from protobuf field <code>bytes channel = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setChannel($var)
    {
        GPBUtil::checkString($var, False);
        $this->channel = $var;

        return $this;
    }

    /**
     *唯一ID(可用MAC、UDID等信息做标识)
     *
     * Generated from protobuf field <code>bytes uuid = 10;</code>
     * @return string
     */
    public function getUuid()
    {
        return $this->uuid;
    }

    /**
     *唯一ID(可用MAC、UDID等信息做标识)
     *
     * Generated from protobuf field <code>bytes uuid = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setUuid($var)
    {
        GPBUtil::checkString($var, False);
        $this->uuid = $var;

        return $this;
    }

    /**
     *CPU类型|频率|核数
     *
     * Generated from protobuf field <code>bytes cpuHardware = 11;</code>
     * @return string
     */
    public function getCpuHardware()
    {
        return $this->cpuHardware;
    }

    /**
     *CPU类型|频率|核数
     *
     * Generated from protobuf field <code>bytes cpuHardware = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setCpuHardware($var)
    {
        GPBUtil::checkString($var, False);
        $this->cpuHardware = $var;

        return $this;
    }

    /**
     *内存大小 单位为MB
     *
     * Generated from protobuf field <code>bytes memory = 12;</code>
     * @return string
     */
    public function getMemory()
    {
        return $this->memory;
    }

    /**
     *内存大小 单位为MB
     *
     * Generated from protobuf field <code>bytes memory = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setMemory($var)
    {
        GPBUtil::checkString($var, False);
        $this->memory = $var;

        return $this;
    }

    /**
     *OpenGL render信息
     *
     * Generated from protobuf field <code>bytes glRender = 13;</code>
     * @return string
     */
    public function getGlRender()
    {
        return $this->glRender;
    }

    /**
     *OpenGL render信息
     *
     * Generated from protobuf field <code>bytes glRender = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setGlRender($var)
    {
        GPBUtil::checkString($var, False);
        $this->glRender = $var;

        return $this;
    }

    /**
     *OpenGL 版本信息
     *
     * Generated from protobuf field <code>bytes glVersion = 14;</code>
     * @return string
     */
    public function getGlVersion()
    {
        return $this->glVersion;
    }

    /**
     *OpenGL 版本信息
     *
     * Generated from protobuf field <code>bytes glVersion = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setGlVersion($var)
    {
        GPBUtil::checkString($var, False);
        $this->glVersion = $var;

        return $this;
    }

    /**
     *设备ID
     *
     * Generated from protobuf field <code>bytes deviceId = 15;</code>
     * @return string
     */
    public function getDeviceId()
    {
        return $this->deviceId;
    }

    /**
     *设备ID
     *
     * Generated from protobuf field <code>bytes deviceId = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceId($var)
    {
        GPBUtil::checkString($var, False);
        $this->deviceId = $var;

        return $this;
    }

}

