<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PlayerProtocol.proto

namespace Logic\Protocol;

/**
 * Protobuf enum <code>Logic\Protocol\PlayerState</code>
 */
class PlayerState
{
    /**
     *正常
     *
     * Generated from protobuf enum <code>PLAYER_STATE_NORMAL = 0;</code>
     */
    const PLAYER_STATE_NORMAL = 0;
    /**
     *限制
     *
     * Generated from protobuf enum <code>PLAYER_STATE_FORBID = 1;</code>
     */
    const PLAYER_STATE_FORBID = 1;
    /**
     *封停
     *
     * Generated from protobuf enum <code>PLAYER_STATE_BAN = 2;</code>
     */
    const PLAYER_STATE_BAN = 2;
    /**
     *初始
     *
     * Generated from protobuf enum <code>PLAYER_STATE_INIT = 3;</code>
     */
    const PLAYER_STATE_INIT = 3;
}

