<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RetCode.proto

namespace Logic\Protocol;

/**
 * Protobuf enum <code>Logic\Protocol\RetCode</code>
 */
class RetCode
{
    /**
     *成功
     *
     * Generated from protobuf enum <code>SUCCESS = 0;</code>
     */
    const SUCCESS = 0;
    /**
     *注册失败
     *
     * Generated from protobuf enum <code>REGIST_FAILED = 4096;</code>
     */
    const REGIST_FAILED = 4096;
    /**
     *登陆失败
     *
     * Generated from protobuf enum <code>LOGIN_FAILED = 65537;</code>
     */
    const LOGIN_FAILED = 65537;
}

