<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PlayerProtocol.proto

namespace GPBMetadata;

class PlayerProtocol
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0af7020a14506c6179657250726f746f636f6c2e70726f746f120e4c6f67" .
            "69632e50726f746f636f6c22530a0a506c61796572496e666f120b0a0375" .
            "496418012001280d12380a0f706c617965724261736963496e666f180220" .
            "01280b321f2e4c6f6769632e50726f746f636f6c2e506c61796572426173" .
            "6963496e666f2283010a0f506c617965724261736963496e666f120c0a04" .
            "6e616d6518012001280c122a0a05737461746518022001280e321b2e4c6f" .
            "6769632e50726f746f636f6c2e506c617965725374617465120b0a037365" .
            "7818032001280d12120a0a72656769737454696d6518042001280412150a" .
            "0d6c6173744c6f67696e54696d651805200128042a6c0a0b506c61796572" .
            "537461746512170a13504c415945525f53544154455f4e4f524d414c1000" .
            "12170a13504c415945525f53544154455f464f52424944100112140a1050" .
            "4c415945525f53544154455f42414e100212150a11504c415945525f5354" .
            "4154455f494e49541003620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

