<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProtocolCmd.proto

namespace GPBMetadata;

class ProtocolCmd
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0afe010a1150726f746f636f6c436d642e70726f746f120e4c6f6769632e" .
            "50726f746f636f6c2ad0010a0b50726f746f636f6c436d64120c0a08434d" .
            "445f545950451000120c0a08434d445f50494e471001120c0a08434d445f" .
            "504f4e47100212180a134d4553534147455f545950455f53595354454d10" .
            "802012130a0e434d445f5245474953545f52455110812012140a0f434d44" .
            "5f5245474953545f5245535010822012120a0d434d445f4c4f47494e5f52" .
            "455110832012130a0e434d445f4c4f47494e5f5245535010842012130a0e" .
            "434d445f4c4f474f55545f52455110852012140a0f434d445f4c4f474f55" .
            "545f52455350108620620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

