<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: User.proto

namespace GPBMetadata;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a480a0a557365722e70726f746f22320a0855736572496e666f120a0a02" .
            "6964180120012805120c0a0474657374180220012805120c0a046e616d65" .
            "180320012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

