// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoginProtocol.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Logic.Protocol {

  /// <summary>Holder for reflection information generated from LoginProtocol.proto</summary>
  public static partial class LoginProtocolReflection {

    #region Descriptor
    /// <summary>File descriptor for LoginProtocol.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LoginProtocolReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNMb2dpblByb3RvY29sLnByb3RvEg5Mb2dpYy5Qcm90b2NvbCKrAgoNUGxh",
            "eWVyRW52SW5mbxIVCg1jbGllbnRWZXJzaW9uGAEgASgMEhIKCnN5c3RlbVNv",
            "ZnQYAiABKAwSFgoOc3lzdGVtSGFyZHdhcmUYAyABKAwSDwoHdGVsZWNvbRgE",
            "IAEoDBIPCgduZXR3b3JrGAUgASgMEhMKC3NjcmVlbldpZHRoGAYgASgMEhQK",
            "DHNjcmVlbkhlaWdodBgHIAEoDBIPCgdkZW5zaXR5GAggASgMEg8KB2NoYW5u",
            "ZWwYCSABKAwSDAoEdXVpZBgKIAEoDBITCgtjcHVIYXJkd2FyZRgLIAEoDBIO",
            "CgZtZW1vcnkYDCABKAwSEAoIZ2xSZW5kZXIYDSABKAwSEQoJZ2xWZXJzaW9u",
            "GA4gASgMEhAKCGRldmljZUlkGA8gASgMIpACCghMb2dpblJlcRIQCgh1c2Vy",
            "bmFtZRgBIAEoDBIQCghwYXNzd29yZBgCIAEoDBIOCgZvcGVuSWQYAyABKAwS",
            "CwoDdUlkGAQgASgFEhIKCmxvZ2luVG9rZW4YBSABKAwSLAoJbG9naW5UeXBl",
            "GAYgASgOMhkuTG9naWMuUHJvdG9jb2wuTG9naW5UeXBlEjQKDXBsYXllckVu",
            "dkluZm8YByABKAsyHS5Mb2dpYy5Qcm90b2NvbC5QbGF5ZXJFbnZJbmZvEhIK",
            "CmRldmljZUNvZGUYCCABKAwSJgoGb3NUeXBlGAkgASgOMhYuTG9naWMuUHJv",
            "dG9jb2wuT1NUeXBlEg8KB2NoYW5uZWwYCiABKA0iCwoJTG9naW5SZXNwKo0B",
            "CglMb2dpblR5cGUSFgoSTE9HSU5fVFlQRV9ERUZBVUxUEAASFgoSTE9HSU5f",
            "VFlQRV9NU0RLX1FREAESFgoSTE9HSU5fVFlQRV9NU0RLX1dYEAISGQoVTE9H",
            "SU5fVFlQRV9NU0RLX0dVRVNUEAMSHQoZTE9HSU5fVFlQRV9USElSRF9QTEFU",
            "Rk9STRAEKnUKBk9TVHlwZRITCg9PU19UWVBFX0RFRkFVTFQQABIOCgpPU19U",
            "WVBFX1BDEAESDwoLT1NfVFlQRV9NQUMQAhIPCgtPU19UWVBFX1dFQhADEg8K",
            "C09TX1RZUEVfSU9TEAQSEwoPT1NfVFlQRV9BTkRST0lEEAViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Logic.Protocol.LoginType), typeof(global::Logic.Protocol.OSType), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Logic.Protocol.PlayerEnvInfo), global::Logic.Protocol.PlayerEnvInfo.Parser, new[]{ "ClientVersion", "SystemSoft", "SystemHardware", "Telecom", "Network", "ScreenWidth", "ScreenHeight", "Density", "Channel", "Uuid", "CpuHardware", "Memory", "GlRender", "GlVersion", "DeviceId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Logic.Protocol.LoginReq), global::Logic.Protocol.LoginReq.Parser, new[]{ "Username", "Password", "OpenId", "UId", "LoginToken", "LoginType", "PlayerEnvInfo", "DeviceCode", "OsType", "Channel" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Logic.Protocol.LoginResp), global::Logic.Protocol.LoginResp.Parser, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///玩家登陆类型
  /// </summary>
  public enum LoginType {
    /// <summary>
    ///默认不使用
    /// </summary>
    [pbr::OriginalName("LOGIN_TYPE_DEFAULT")] Default = 0,
    /// <summary>
    ///QQ平台
    /// </summary>
    [pbr::OriginalName("LOGIN_TYPE_MSDK_QQ")] MsdkQq = 1,
    /// <summary>
    ///微信平台
    /// </summary>
    [pbr::OriginalName("LOGIN_TYPE_MSDK_WX")] MsdkWx = 2,
    /// <summary>
    ///游客访问
    /// </summary>
    [pbr::OriginalName("LOGIN_TYPE_MSDK_GUEST")] MsdkGuest = 3,
    /// <summary>
    ///第三方平台
    /// </summary>
    [pbr::OriginalName("LOGIN_TYPE_THIRD_PLATFORM")] ThirdPlatform = 4,
  }

  /// <summary>
  ///终端类型
  /// </summary>
  public enum OSType {
    /// <summary>
    ///默认不使用
    /// </summary>
    [pbr::OriginalName("OS_TYPE_DEFAULT")] Default = 0,
    /// <summary>
    ///PC
    /// </summary>
    [pbr::OriginalName("OS_TYPE_PC")] Pc = 1,
    /// <summary>
    ///Mac
    /// </summary>
    [pbr::OriginalName("OS_TYPE_MAC")] Mac = 2,
    /// <summary>
    ///web
    /// </summary>
    [pbr::OriginalName("OS_TYPE_WEB")] Web = 3,
    /// <summary>
    ///IOS
    /// </summary>
    [pbr::OriginalName("OS_TYPE_IOS")] Ios = 4,
    /// <summary>
    ///安卓
    /// </summary>
    [pbr::OriginalName("OS_TYPE_ANDROID")] Android = 5,
  }

  #endregion

  #region Messages
  /// <summary>
  ///玩家的设备相关信息，用于日志统计的信息（在玩家注册和登陆时上报该内容）
  /// </summary>
  public sealed partial class PlayerEnvInfo : pb::IMessage<PlayerEnvInfo> {
    private static readonly pb::MessageParser<PlayerEnvInfo> _parser = new pb::MessageParser<PlayerEnvInfo>(() => new PlayerEnvInfo());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PlayerEnvInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Logic.Protocol.LoginProtocolReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerEnvInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerEnvInfo(PlayerEnvInfo other) : this() {
      clientVersion_ = other.clientVersion_;
      systemSoft_ = other.systemSoft_;
      systemHardware_ = other.systemHardware_;
      telecom_ = other.telecom_;
      network_ = other.network_;
      screenWidth_ = other.screenWidth_;
      screenHeight_ = other.screenHeight_;
      density_ = other.density_;
      channel_ = other.channel_;
      uuid_ = other.uuid_;
      cpuHardware_ = other.cpuHardware_;
      memory_ = other.memory_;
      glRender_ = other.glRender_;
      glVersion_ = other.glVersion_;
      deviceId_ = other.deviceId_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerEnvInfo Clone() {
      return new PlayerEnvInfo(this);
    }

    /// <summary>Field number for the "clientVersion" field.</summary>
    public const int ClientVersionFieldNumber = 1;
    private pb::ByteString clientVersion_ = pb::ByteString.Empty;
    /// <summary>
    ///客户端版本
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString ClientVersion {
      get { return clientVersion_; }
      set {
        clientVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "systemSoft" field.</summary>
    public const int SystemSoftFieldNumber = 2;
    private pb::ByteString systemSoft_ = pb::ByteString.Empty;
    /// <summary>
    ///操作系统版本
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString SystemSoft {
      get { return systemSoft_; }
      set {
        systemSoft_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "systemHardware" field.</summary>
    public const int SystemHardwareFieldNumber = 3;
    private pb::ByteString systemHardware_ = pb::ByteString.Empty;
    /// <summary>
    ///终端机型设备
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString SystemHardware {
      get { return systemHardware_; }
      set {
        systemHardware_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "telecom" field.</summary>
    public const int TelecomFieldNumber = 4;
    private pb::ByteString telecom_ = pb::ByteString.Empty;
    /// <summary>
    ///运营商
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Telecom {
      get { return telecom_; }
      set {
        telecom_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "network" field.</summary>
    public const int NetworkFieldNumber = 5;
    private pb::ByteString network_ = pb::ByteString.Empty;
    /// <summary>
    ///3G/4G/WIFI/2G
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Network {
      get { return network_; }
      set {
        network_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "screenWidth" field.</summary>
    public const int ScreenWidthFieldNumber = 6;
    private pb::ByteString screenWidth_ = pb::ByteString.Empty;
    /// <summary>
    ///屏幕宽度
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString ScreenWidth {
      get { return screenWidth_; }
      set {
        screenWidth_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "screenHeight" field.</summary>
    public const int ScreenHeightFieldNumber = 7;
    private pb::ByteString screenHeight_ = pb::ByteString.Empty;
    /// <summary>
    ///屏幕高度
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString ScreenHeight {
      get { return screenHeight_; }
      set {
        screenHeight_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "density" field.</summary>
    public const int DensityFieldNumber = 8;
    private pb::ByteString density_ = pb::ByteString.Empty;
    /// <summary>
    ///屏幕像素密度
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Density {
      get { return density_; }
      set {
        density_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "channel" field.</summary>
    public const int ChannelFieldNumber = 9;
    private pb::ByteString channel_ = pb::ByteString.Empty;
    /// <summary>
    ///注册渠道
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Channel {
      get { return channel_; }
      set {
        channel_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "uuid" field.</summary>
    public const int UuidFieldNumber = 10;
    private pb::ByteString uuid_ = pb::ByteString.Empty;
    /// <summary>
    ///唯一ID(可用MAC、UDID等信息做标识)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Uuid {
      get { return uuid_; }
      set {
        uuid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "cpuHardware" field.</summary>
    public const int CpuHardwareFieldNumber = 11;
    private pb::ByteString cpuHardware_ = pb::ByteString.Empty;
    /// <summary>
    ///CPU类型|频率|核数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString CpuHardware {
      get { return cpuHardware_; }
      set {
        cpuHardware_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "memory" field.</summary>
    public const int MemoryFieldNumber = 12;
    private pb::ByteString memory_ = pb::ByteString.Empty;
    /// <summary>
    ///内存大小 单位为MB
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Memory {
      get { return memory_; }
      set {
        memory_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "glRender" field.</summary>
    public const int GlRenderFieldNumber = 13;
    private pb::ByteString glRender_ = pb::ByteString.Empty;
    /// <summary>
    ///OpenGL render信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString GlRender {
      get { return glRender_; }
      set {
        glRender_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "glVersion" field.</summary>
    public const int GlVersionFieldNumber = 14;
    private pb::ByteString glVersion_ = pb::ByteString.Empty;
    /// <summary>
    ///OpenGL 版本信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString GlVersion {
      get { return glVersion_; }
      set {
        glVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "deviceId" field.</summary>
    public const int DeviceIdFieldNumber = 15;
    private pb::ByteString deviceId_ = pb::ByteString.Empty;
    /// <summary>
    ///设备ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString DeviceId {
      get { return deviceId_; }
      set {
        deviceId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PlayerEnvInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PlayerEnvInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ClientVersion != other.ClientVersion) return false;
      if (SystemSoft != other.SystemSoft) return false;
      if (SystemHardware != other.SystemHardware) return false;
      if (Telecom != other.Telecom) return false;
      if (Network != other.Network) return false;
      if (ScreenWidth != other.ScreenWidth) return false;
      if (ScreenHeight != other.ScreenHeight) return false;
      if (Density != other.Density) return false;
      if (Channel != other.Channel) return false;
      if (Uuid != other.Uuid) return false;
      if (CpuHardware != other.CpuHardware) return false;
      if (Memory != other.Memory) return false;
      if (GlRender != other.GlRender) return false;
      if (GlVersion != other.GlVersion) return false;
      if (DeviceId != other.DeviceId) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ClientVersion.Length != 0) hash ^= ClientVersion.GetHashCode();
      if (SystemSoft.Length != 0) hash ^= SystemSoft.GetHashCode();
      if (SystemHardware.Length != 0) hash ^= SystemHardware.GetHashCode();
      if (Telecom.Length != 0) hash ^= Telecom.GetHashCode();
      if (Network.Length != 0) hash ^= Network.GetHashCode();
      if (ScreenWidth.Length != 0) hash ^= ScreenWidth.GetHashCode();
      if (ScreenHeight.Length != 0) hash ^= ScreenHeight.GetHashCode();
      if (Density.Length != 0) hash ^= Density.GetHashCode();
      if (Channel.Length != 0) hash ^= Channel.GetHashCode();
      if (Uuid.Length != 0) hash ^= Uuid.GetHashCode();
      if (CpuHardware.Length != 0) hash ^= CpuHardware.GetHashCode();
      if (Memory.Length != 0) hash ^= Memory.GetHashCode();
      if (GlRender.Length != 0) hash ^= GlRender.GetHashCode();
      if (GlVersion.Length != 0) hash ^= GlVersion.GetHashCode();
      if (DeviceId.Length != 0) hash ^= DeviceId.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ClientVersion.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(ClientVersion);
      }
      if (SystemSoft.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(SystemSoft);
      }
      if (SystemHardware.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(SystemHardware);
      }
      if (Telecom.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(Telecom);
      }
      if (Network.Length != 0) {
        output.WriteRawTag(42);
        output.WriteBytes(Network);
      }
      if (ScreenWidth.Length != 0) {
        output.WriteRawTag(50);
        output.WriteBytes(ScreenWidth);
      }
      if (ScreenHeight.Length != 0) {
        output.WriteRawTag(58);
        output.WriteBytes(ScreenHeight);
      }
      if (Density.Length != 0) {
        output.WriteRawTag(66);
        output.WriteBytes(Density);
      }
      if (Channel.Length != 0) {
        output.WriteRawTag(74);
        output.WriteBytes(Channel);
      }
      if (Uuid.Length != 0) {
        output.WriteRawTag(82);
        output.WriteBytes(Uuid);
      }
      if (CpuHardware.Length != 0) {
        output.WriteRawTag(90);
        output.WriteBytes(CpuHardware);
      }
      if (Memory.Length != 0) {
        output.WriteRawTag(98);
        output.WriteBytes(Memory);
      }
      if (GlRender.Length != 0) {
        output.WriteRawTag(106);
        output.WriteBytes(GlRender);
      }
      if (GlVersion.Length != 0) {
        output.WriteRawTag(114);
        output.WriteBytes(GlVersion);
      }
      if (DeviceId.Length != 0) {
        output.WriteRawTag(122);
        output.WriteBytes(DeviceId);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ClientVersion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(ClientVersion);
      }
      if (SystemSoft.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(SystemSoft);
      }
      if (SystemHardware.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(SystemHardware);
      }
      if (Telecom.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Telecom);
      }
      if (Network.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Network);
      }
      if (ScreenWidth.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(ScreenWidth);
      }
      if (ScreenHeight.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(ScreenHeight);
      }
      if (Density.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Density);
      }
      if (Channel.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Channel);
      }
      if (Uuid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Uuid);
      }
      if (CpuHardware.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(CpuHardware);
      }
      if (Memory.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Memory);
      }
      if (GlRender.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(GlRender);
      }
      if (GlVersion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(GlVersion);
      }
      if (DeviceId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(DeviceId);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PlayerEnvInfo other) {
      if (other == null) {
        return;
      }
      if (other.ClientVersion.Length != 0) {
        ClientVersion = other.ClientVersion;
      }
      if (other.SystemSoft.Length != 0) {
        SystemSoft = other.SystemSoft;
      }
      if (other.SystemHardware.Length != 0) {
        SystemHardware = other.SystemHardware;
      }
      if (other.Telecom.Length != 0) {
        Telecom = other.Telecom;
      }
      if (other.Network.Length != 0) {
        Network = other.Network;
      }
      if (other.ScreenWidth.Length != 0) {
        ScreenWidth = other.ScreenWidth;
      }
      if (other.ScreenHeight.Length != 0) {
        ScreenHeight = other.ScreenHeight;
      }
      if (other.Density.Length != 0) {
        Density = other.Density;
      }
      if (other.Channel.Length != 0) {
        Channel = other.Channel;
      }
      if (other.Uuid.Length != 0) {
        Uuid = other.Uuid;
      }
      if (other.CpuHardware.Length != 0) {
        CpuHardware = other.CpuHardware;
      }
      if (other.Memory.Length != 0) {
        Memory = other.Memory;
      }
      if (other.GlRender.Length != 0) {
        GlRender = other.GlRender;
      }
      if (other.GlVersion.Length != 0) {
        GlVersion = other.GlVersion;
      }
      if (other.DeviceId.Length != 0) {
        DeviceId = other.DeviceId;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            ClientVersion = input.ReadBytes();
            break;
          }
          case 18: {
            SystemSoft = input.ReadBytes();
            break;
          }
          case 26: {
            SystemHardware = input.ReadBytes();
            break;
          }
          case 34: {
            Telecom = input.ReadBytes();
            break;
          }
          case 42: {
            Network = input.ReadBytes();
            break;
          }
          case 50: {
            ScreenWidth = input.ReadBytes();
            break;
          }
          case 58: {
            ScreenHeight = input.ReadBytes();
            break;
          }
          case 66: {
            Density = input.ReadBytes();
            break;
          }
          case 74: {
            Channel = input.ReadBytes();
            break;
          }
          case 82: {
            Uuid = input.ReadBytes();
            break;
          }
          case 90: {
            CpuHardware = input.ReadBytes();
            break;
          }
          case 98: {
            Memory = input.ReadBytes();
            break;
          }
          case 106: {
            GlRender = input.ReadBytes();
            break;
          }
          case 114: {
            GlVersion = input.ReadBytes();
            break;
          }
          case 122: {
            DeviceId = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///登陆请求
  /// </summary>
  public sealed partial class LoginReq : pb::IMessage<LoginReq> {
    private static readonly pb::MessageParser<LoginReq> _parser = new pb::MessageParser<LoginReq>(() => new LoginReq());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<LoginReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Logic.Protocol.LoginProtocolReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LoginReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LoginReq(LoginReq other) : this() {
      username_ = other.username_;
      password_ = other.password_;
      openId_ = other.openId_;
      uId_ = other.uId_;
      loginToken_ = other.loginToken_;
      loginType_ = other.loginType_;
      PlayerEnvInfo = other.playerEnvInfo_ != null ? other.PlayerEnvInfo.Clone() : null;
      deviceCode_ = other.deviceCode_;
      osType_ = other.osType_;
      channel_ = other.channel_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LoginReq Clone() {
      return new LoginReq(this);
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 1;
    private pb::ByteString username_ = pb::ByteString.Empty;
    /// <summary>
    ///用户名   
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "password" field.</summary>
    public const int PasswordFieldNumber = 2;
    private pb::ByteString password_ = pb::ByteString.Empty;
    /// <summary>
    ///密码
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "openId" field.</summary>
    public const int OpenIdFieldNumber = 3;
    private pb::ByteString openId_ = pb::ByteString.Empty;
    /// <summary>
    ///openId，通常情况下openID为第三方渠道请求后获得的唯一标识，根据业务逻辑和接入渠道情况自行定义
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString OpenId {
      get { return openId_; }
      set {
        openId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "uId" field.</summary>
    public const int UIdFieldNumber = 4;
    private int uId_;
    /// <summary>
    ///uId，如果在有单独登陆服务器的情况下，通常uId作为唯一ID标识
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UId {
      get { return uId_; }
      set {
        uId_ = value;
      }
    }

    /// <summary>Field number for the "loginToken" field.</summary>
    public const int LoginTokenFieldNumber = 5;
    private pb::ByteString loginToken_ = pb::ByteString.Empty;
    /// <summary>
    ///登陆Token，通常有登陆服务器的情况下，登陆服务器返回的Token，并用这个Token和网关进行验证
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString LoginToken {
      get { return loginToken_; }
      set {
        loginToken_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "loginType" field.</summary>
    public const int LoginTypeFieldNumber = 6;
    private global::Logic.Protocol.LoginType loginType_ = 0;
    /// <summary>
    ///登陆类型（参照上面的枚举）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Logic.Protocol.LoginType LoginType {
      get { return loginType_; }
      set {
        loginType_ = value;
      }
    }

    /// <summary>Field number for the "playerEnvInfo" field.</summary>
    public const int PlayerEnvInfoFieldNumber = 7;
    private global::Logic.Protocol.PlayerEnvInfo playerEnvInfo_;
    /// <summary>
    ///玩家的机器相关信息（用于数据统计）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Logic.Protocol.PlayerEnvInfo PlayerEnvInfo {
      get { return playerEnvInfo_; }
      set {
        playerEnvInfo_ = value;
      }
    }

    /// <summary>Field number for the "deviceCode" field.</summary>
    public const int DeviceCodeFieldNumber = 8;
    private pb::ByteString deviceCode_ = pb::ByteString.Empty;
    /// <summary>
    ///用于消息推送使用，一般来说用deviceId即可
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString DeviceCode {
      get { return deviceCode_; }
      set {
        deviceCode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "osType" field.</summary>
    public const int OsTypeFieldNumber = 9;
    private global::Logic.Protocol.OSType osType_ = 0;
    /// <summary>
    ///玩家终端类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Logic.Protocol.OSType OsType {
      get { return osType_; }
      set {
        osType_ = value;
      }
    }

    /// <summary>Field number for the "channel" field.</summary>
    public const int ChannelFieldNumber = 10;
    private uint channel_;
    /// <summary>
    ///第三方渠道号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Channel {
      get { return channel_; }
      set {
        channel_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as LoginReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(LoginReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Username != other.Username) return false;
      if (Password != other.Password) return false;
      if (OpenId != other.OpenId) return false;
      if (UId != other.UId) return false;
      if (LoginToken != other.LoginToken) return false;
      if (LoginType != other.LoginType) return false;
      if (!object.Equals(PlayerEnvInfo, other.PlayerEnvInfo)) return false;
      if (DeviceCode != other.DeviceCode) return false;
      if (OsType != other.OsType) return false;
      if (Channel != other.Channel) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Username.Length != 0) hash ^= Username.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      if (OpenId.Length != 0) hash ^= OpenId.GetHashCode();
      if (UId != 0) hash ^= UId.GetHashCode();
      if (LoginToken.Length != 0) hash ^= LoginToken.GetHashCode();
      if (LoginType != 0) hash ^= LoginType.GetHashCode();
      if (playerEnvInfo_ != null) hash ^= PlayerEnvInfo.GetHashCode();
      if (DeviceCode.Length != 0) hash ^= DeviceCode.GetHashCode();
      if (OsType != 0) hash ^= OsType.GetHashCode();
      if (Channel != 0) hash ^= Channel.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Username.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Username);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Password);
      }
      if (OpenId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(OpenId);
      }
      if (UId != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(UId);
      }
      if (LoginToken.Length != 0) {
        output.WriteRawTag(42);
        output.WriteBytes(LoginToken);
      }
      if (LoginType != 0) {
        output.WriteRawTag(48);
        output.WriteEnum((int) LoginType);
      }
      if (playerEnvInfo_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(PlayerEnvInfo);
      }
      if (DeviceCode.Length != 0) {
        output.WriteRawTag(66);
        output.WriteBytes(DeviceCode);
      }
      if (OsType != 0) {
        output.WriteRawTag(72);
        output.WriteEnum((int) OsType);
      }
      if (Channel != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(Channel);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Username);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Password);
      }
      if (OpenId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(OpenId);
      }
      if (UId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UId);
      }
      if (LoginToken.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(LoginToken);
      }
      if (LoginType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) LoginType);
      }
      if (playerEnvInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PlayerEnvInfo);
      }
      if (DeviceCode.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(DeviceCode);
      }
      if (OsType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) OsType);
      }
      if (Channel != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Channel);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(LoginReq other) {
      if (other == null) {
        return;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
      if (other.OpenId.Length != 0) {
        OpenId = other.OpenId;
      }
      if (other.UId != 0) {
        UId = other.UId;
      }
      if (other.LoginToken.Length != 0) {
        LoginToken = other.LoginToken;
      }
      if (other.LoginType != 0) {
        LoginType = other.LoginType;
      }
      if (other.playerEnvInfo_ != null) {
        if (playerEnvInfo_ == null) {
          playerEnvInfo_ = new global::Logic.Protocol.PlayerEnvInfo();
        }
        PlayerEnvInfo.MergeFrom(other.PlayerEnvInfo);
      }
      if (other.DeviceCode.Length != 0) {
        DeviceCode = other.DeviceCode;
      }
      if (other.OsType != 0) {
        OsType = other.OsType;
      }
      if (other.Channel != 0) {
        Channel = other.Channel;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Username = input.ReadBytes();
            break;
          }
          case 18: {
            Password = input.ReadBytes();
            break;
          }
          case 26: {
            OpenId = input.ReadBytes();
            break;
          }
          case 32: {
            UId = input.ReadInt32();
            break;
          }
          case 42: {
            LoginToken = input.ReadBytes();
            break;
          }
          case 48: {
            loginType_ = (global::Logic.Protocol.LoginType) input.ReadEnum();
            break;
          }
          case 58: {
            if (playerEnvInfo_ == null) {
              playerEnvInfo_ = new global::Logic.Protocol.PlayerEnvInfo();
            }
            input.ReadMessage(playerEnvInfo_);
            break;
          }
          case 66: {
            DeviceCode = input.ReadBytes();
            break;
          }
          case 72: {
            osType_ = (global::Logic.Protocol.OSType) input.ReadEnum();
            break;
          }
          case 80: {
            Channel = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///登陆响应
  /// </summary>
  public sealed partial class LoginResp : pb::IMessage<LoginResp> {
    private static readonly pb::MessageParser<LoginResp> _parser = new pb::MessageParser<LoginResp>(() => new LoginResp());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<LoginResp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Logic.Protocol.LoginProtocolReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LoginResp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LoginResp(LoginResp other) : this() {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LoginResp Clone() {
      return new LoginResp(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as LoginResp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(LoginResp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(LoginResp other) {
      if (other == null) {
        return;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
