// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtocolCmd.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Logic.Protocol {

  /// <summary>Holder for reflection information generated from ProtocolCmd.proto</summary>
  public static partial class ProtocolCmdReflection {

    #region Descriptor
    /// <summary>File descriptor for ProtocolCmd.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtocolCmdReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFQcm90b2NvbENtZC5wcm90bxIOTG9naWMuUHJvdG9jb2wq0AEKC1Byb3Rv",
            "Y29sQ21kEgwKCENNRF9UWVBFEAASDAoIQ01EX1BJTkcQARIMCghDTURfUE9O",
            "RxACEhgKE01FU1NBR0VfVFlQRV9TWVNURU0QgCASEwoOQ01EX1JFR0lTVF9S",
            "RVEQgSASFAoPQ01EX1JFR0lTVF9SRVNQEIIgEhIKDUNNRF9MT0dJTl9SRVEQ",
            "gyASEwoOQ01EX0xPR0lOX1JFU1AQhCASEwoOQ01EX0xPR09VVF9SRVEQhSAS",
            "FAoPQ01EX0xPR09VVF9SRVNQEIYgYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Logic.Protocol.ProtocolCmd), }, null));
    }
    #endregion

  }
  #region Enums
  public enum ProtocolCmd {
    [pbr::OriginalName("CMD_TYPE")] CmdType = 0,
    /// <summary>
    ///心跳
    /// </summary>
    [pbr::OriginalName("CMD_PING")] CmdPing = 1,
    [pbr::OriginalName("CMD_PONG")] CmdPong = 2,
    /// <summary>
    ///4位作为CMD命令，不同开头功能不同
    /// </summary>
    [pbr::OriginalName("MESSAGE_TYPE_SYSTEM")] MessageTypeSystem = 4096,
    /// <summary>
    ///注册
    /// </summary>
    [pbr::OriginalName("CMD_REGIST_REQ")] CmdRegistReq = 4097,
    [pbr::OriginalName("CMD_REGIST_RESP")] CmdRegistResp = 4098,
    /// <summary>
    ///登陆
    /// </summary>
    [pbr::OriginalName("CMD_LOGIN_REQ")] CmdLoginReq = 4099,
    [pbr::OriginalName("CMD_LOGIN_RESP")] CmdLoginResp = 4100,
    /// <summary>
    ///退出
    /// </summary>
    [pbr::OriginalName("CMD_LOGOUT_REQ")] CmdLogoutReq = 4101,
    [pbr::OriginalName("CMD_LOGOUT_RESP")] CmdLogoutResp = 4102,
  }

  #endregion

}

#endregion Designer generated code
