// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RetCode.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Logic.Protocol {

  /// <summary>Holder for reflection information generated from RetCode.proto</summary>
  public static partial class RetCodeReflection {

    #region Descriptor
    /// <summary>File descriptor for RetCode.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RetCodeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1SZXRDb2RlLnByb3RvEg5Mb2dpYy5Qcm90b2NvbCoqCgdSZXRDb2RlEgsK",
            "B1NVQ0NFU1MQABISCg1SRUdJU1RfRkFJTEVEEIAgYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Logic.Protocol.RetCode), }, null));
    }
    #endregion

  }
  #region Enums
  public enum RetCode {
    /// <summary>
    ///成功
    /// </summary>
    [pbr::OriginalName("SUCCESS")] Success = 0,
    /// <summary>
    ///注册失败
    /// </summary>
    [pbr::OriginalName("REGIST_FAILED")] RegistFailed = 4096,
  }

  #endregion

}

#endregion Designer generated code
